In [15]:
import numpy as np
import pandas as pd

In [15]:
# Part 1: NumPy Array Operations

In [16]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [17]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7

In [18]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(temperatures_f)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [19]:
print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144

In [20]:
first_three_days = temperatures_w1[:3]

print("First Three Days:", first_three_days)

First Three Days: [22.5 25.3 20.8]

In [21]:
weekend = temperatures_w1[-2:]

print("Weekend Temperatures:", weekend)

Weekend Temperatures: [24.8 21.9]

In [22]:
middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:", middle_three_days)

Middle Three Days: [20.8 23.4 26.1]

In [23]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print("Temperatures for Two Weeks:")
print(temperatures)

Temperatures for Two Weeks:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [24]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14

In [25]:
week1 = temperatures[0, :]

print("Week 1 Temperatures:", week1)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [26]:
week2 = temperatures[1, :]

print("Week 2 Temperatures:", week2)

Week 2 Temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [27]:
weekends = temperatures[:, -2:]

print("Weekend Temperatures for Both Weeks:")
print(weekends)

Weekend Temperatures for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]

In [ ]:
#Part 2: Pandas Series

In [28]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Student Marks:")
print(marks)

Student Marks:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [29]:
first_rank = marks.iloc[0]

print("First Rank Marks:", first_rank)

First Rank Marks: 95

In [30]:
top_three = marks.loc['Rank1':'Rank3']

print("Top 3 Students:")
print(top_three)

Top 3 Students:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [31]:
third_rank = marks.iloc[2]

print("Third Rank Marks:", third_rank)

Third Rank Marks: 89

In [32]:
high_marks = marks[marks > 90]

print("Students with Marks Greater Than 90:")
print(high_marks)

Students with Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64

In [33]:
marks.loc['Rank1'] = 100

print("Updated Student Marks:")
print(marks)

Updated Student Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [34]:
marks = marks.drop('Rank5')

print("Marks After Removing Rank5:")
print(marks)

Marks After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [35]:
cgpa = marks / 10

print("Student CGPA:")
print(cgpa)

Student CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [ ]:
#Part 3: Pandas DataFrame

In [38]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics',
        'Furniture', 'Clothing', 'Electronics',
        'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [41]:
print("First 5 Rows:")
display(transactions.head())

First 5 Rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [42]:
print("Last 5 Rows:")
display(transactions.tail())

Last 5 Rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [43]:
print("Shape:", transactions.shape)

Shape: (10, 4)

In [44]:
print("Column Names:", transactions.columns)

Column Names: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [45]:
print("Data Types:")
print(transactions.dtypes)

Data Types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [46]:
print("DataFrame Information:")
transactions.info()

DataFrame Information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

In [47]:
selected_columns = transactions[['ProductCategory', 'Amount']]

print("Selected Columns:")
display(selected_columns)

Selected Columns:

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [48]:
last_three_columns = transactions.iloc[:, -3:]

print("Last Three Columns:")
display(last_three_columns)

Last Three Columns:

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [49]:
filtered_transactions = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print("Filtered Transactions:")
display(filtered_transactions)

Filtered Transactions:

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [52]:
category_counts = transactions['ProductCategory'].value_counts()

print("Product Category Counts:")
print(category_counts)

Product Category Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [53]:
unique_regions = transactions['Region'].unique()

print("Unique Regions:")
print(unique_regions)

Unique Regions:
<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [54]:
region_mean = transactions.groupby('Region')['Amount'].mean()

print("Average Transaction Amount by Region:")
print(region_mean)

Average Transaction Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [55]:
transactions.loc[
    transactions['TransactionID'] == 102, 'Amount'
] = 165

print("Updated Transaction:")
display(transactions[transactions['TransactionID'] == 102])

Updated Transaction:

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165

In [56]:
transactions['Discount'] = transactions['Amount'] * 0.10

print("Transactions with Discount:")
display(transactions)

Transactions with Discount:

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [57]:
transactions = transactions.drop(
    transactions[transactions['TransactionID'] == 109].index
)

print("Transactions After Removing TransactionID 109:")
display(transactions)

Transactions After Removing TransactionID 109:

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [58]:
transactions = transactions.drop(columns=['Discount'])

print("Transactions After Removing Discount Column:")
display(transactions)

Transactions After Removing Discount Column:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [59]:
print("Final DataFrame Shape:", transactions.shape)
print("Final Column Names:", transactions.columns.tolist())

Final DataFrame Shape: (9, 4)
Final Column Names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']